# Generated by Django 3.1.3 on 2020-11-22 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History_of_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_name', models.CharField(blank=True, max_length=50, null=True)),
                ('after_name', models.CharField(blank=True, max_length=50, null=True)),
                ('before_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('after_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('before_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('after_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('before_orderType', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Bulk', 'Bulk'), ('Both', 'Both')], max_length=10, null=True)),
                ('after_orderType', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Bulk', 'Bulk'), ('Both', 'Both')], max_length=10, null=True)),
                ('before_bulkMinimum', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('after_bulkMinimum', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('before_bulkPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('after_bulkPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('before_description', models.TextField(blank=True, null=True)),
                ('after_description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items')),
                ('name', models.CharField(max_length=50)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('orderType', models.CharField(choices=[('Individual', 'Individual'), ('Bulk', 'Bulk'), ('Both', 'Both')], default='Individual', max_length=10)),
                ('bulkMinimum', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('bulkPrice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('description', models.TextField()),
                ('history', models.ManyToManyField(to='api.History_of_Item')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Other', 'Other')], default='Other', max_length=10)),
                ('items', models.ManyToManyField(to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.DateField(auto_now=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Vendor', 'Vendor'), ('Employee', 'Employee')], default='Employee', max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(through='api.Association', to='api.Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
