# Generated by Django 3.1.3 on 2020-11-22 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_of_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_name', models.CharField(blank=True, max_length=50, null=True)),
                ('after_name', models.CharField(blank=True, max_length=50, null=True)),
                ('before_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('after_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0)])),
                ('before_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('after_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('before_description', models.TextField(blank=True, null=True)),
                ('after_description', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AddField(
            model_name='item',
            name='history',
            field=models.ManyToManyField(to='api.History_of_Item'),
        ),
    ]
