env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
ignorePatterns: ["App.test.js"]
rules: {}
settings:
  react:
    createClass: "createReactClass"
    pragma: "React"
    fragment: "Fragment"
    version: "detect"
    flowVersion: "0.53" 