name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        node-version: ['10', '11', '12' ]
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Set up Node ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Backend - Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # [TODO] Install dependecies for Frontend
      # - name: Frontend - Install Dependencies
      #   working-directory: ./frontend
      #   run: ...

      # [TODO] Update coverage to include Frontend

      - name: Test - Pytest
        run: pytest test_dummy.py --junitxml=report.xml

      - name: Test - Jest
        working-directory: ./frontend
        run: |
          npm install
          npm test

      - name: Linter - Black
        uses: lgeiger/black-action@master
        with:
          args: "*/*.py --check"

      - name: Linter - JS Lint
        uses: goto-bus-stop/standard-action@v1
        with:
          files: ./frontend/src/*.js
          annotate: true

      - name: Bug Finder - Pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reporter: github-pr-check

      - name: Bug Finder - JSHint
        uses: moneyforward/jshint-action@v0
        with:
          files: ./frontend/src/*.js